#!/bin/bash
# File: help.sh
# DLMap: Help/Usage Documentation - Nmap Style

echo ""
echo "DLMap: Deep Link Map - Advanced APK Security Scanner 1.00"
echo "( https://dlmap.sh )"
echo "Usage: dlmap [Scan Type] <Target Specification> [Options]"
echo ""
echo "TARGET SPECIFICATION:"
echo "  /path/to/file.apk    Path to the Android APK file to analyze."
echo ""
echo "SCAN TECHNIQUES AND ENGINE OPTIONS:"
echo "  -A                 Aggressive scan (Equivalent to -sS -sI -sC -sN -sB -sP -sU)."
echo ""
echo "NEW ADVANCED SCRIPTS (DSE - DLMap Scripting Engine):"
echo "  -sB                Bytecode Analysis Readiness (NEW: Foundation for MobSF-level checks)."
echo "  -sC                Exported Components Scan (NEW: Exposed Activities, Providers, Receivers)."
echo "  -sN                Network Security Check (NEW: Cleartext traffic, Certificate issues)."
echo ""
echo "CORE DLMAP SCRIPTS (Refined):"
echo "  -sI                Integrity Check (Min/Target SDK compliance, Security Headers)."
echo "  -sS                Secrets Search (High-Confidence regex for API keys, tokens, hardcoded data)."
echo "  -sP                Permissions Scan (Highlights high-risk permissions, permission misuse)."
echo "  -sU                URI Scheme Check (Finds deep links, Intent Filter entry points)."
echo ""
echo "EXAMPLES:"
echo "  dlmap /sdcard/app.apk -A"
echo "  dlmap -sS -sI /path/to/target.apk"
echo "  dlmap -h"
echo ""

